sender_secret = "1234567890"
sender_balance = "100"
transfer_amount = "25"
recipient_address = "9876543210"
sender_nonce = "1"
input_commitment = "0"
output_commitment_sender = "0"
output_commitment_recipient = "0"
nullifier = "0"
new_nonce = "2"
